### ISSUE TITLE
BC bug

### ISSUE THREAD

**Issue by MuMuMuCODE** [Akiranya/GemsEconomy#4]
In BC mode, execute the command /eco take A 100 to player A on server A. At this time, if player A’s balance is insufficient, player B executes the command /pay A 100 on server B, which may cause player A’s balance to not be deduct

**Comment by MuMuMuCODE** [comment]
Should this be a concurrency issue?

**Comment by Akiranya** [comment]
Currently, GemsEconomy depends on https://github.com/Phoenix616/ConnectorPlugin to sync data across the server network if ConnectorPlugin is properly installed and configured on your proxy and backend servers (please use `redis` mode if possible. BungeeCord/Waterfall/Velocity doesn't send plugin messages to empty backend servers). Otherwise, GemsEconomy will simply disable the data sync function silently.

I'm gonna rewrite the messaging system for the data sync feature in the future so ConnectorPlugin probably will not be needed anymore (a better and more modern external library might be used)

**Comment by MuMuMuCODE** [comment]
Only need to install ConnectorPlugin, can the data be synchronized?

**Comment by Akiranya** [comment]
Yes if you configure ConnectorPlugin properly (as I said, follow the official guide of ConnectorPlugin and use `redis` as the messaging method in its config).

GemsEconomy is coded with network usage and concurrency in mind.
